markdown: kramdown
kramdown:
  hard_wrap: false
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
title: There's Nothing Here
description: There's Nothing There
author: sharp-tailed
github:
  home_url: index.html
  tor_mirror_url: nopeycia5rezyl7ydabjobcfreax6upf3g24q4rzeogskzilqffdj6ad.onion
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      sitemap: true
locale: "en-US"
